from unittest import TestCase


class ProblemOneTests(TestCase):
    def test_x(self):
        self.fail('x')
